### ISSUE TITLE
Solved: fritzbox returned this {"msg":"get error in http request","function":"get_login_state","error":{}}

### ISSUE THREAD

**Issue by tonyblue2** [foxthefox/ioBroker.fritzdect#204]
Hallo,

zunächst vielen Dank für diesen tollen Adapter.

Mein Problem: Ich bekomme von fritzdect ständig (beim Start und dann bei jedem Polling) reihenweise folgende Fehlermeldung:

fritzbox returned this {"msg":"get error in http request","function":"get_login_state","error":{}}
error: fritzdect.0 (2949) no response part in returned message
--
```
2021-09-01 10:17:19.030  - info:  fritzdect.0 (2949) starting. Version 2.1.15 in  /opt/iobroker/node_modules/iobroker.fritzdect, node: v12.22.6,  js-controller: 3.3.15
2021-09-01 10:17:19.037  - info: fritzdect.0 (2949) fritzdect entered ready
2021-09-01 10:17:19.049  - info: fritzdect.0 (2949) fritzdect uses USER: iobroker
2021-09-01 10:17:19.049  - info: fritzdect.0 (2949) start creating devices/groups
2021-09-01 10:17:19.053  - error: fritzdect.0 (2949) fritzbox returned this {"msg":"get error in http request","function":"get_login_state","error":{}}
2021-09-01 10:17:19.054  - error: fritzdect.0 (2949) no response part in returned message
2021-09-01 10:17:19.054  - info: fritzdect.0 (2949) finished creating devices/groups (if any)
2021-09-01 10:17:19.054  - info: fritzdect.0 (2949) start creating templates
2021-09-01 10:17:19.054  - error: fritzdect.0 (2949) fritzbox returned this {"msg":"get error in http request","function":"get_login_state","error":{}}
2021-09-01 10:17:19.054  - error: fritzdect.0 (2949) no response part in returned message
2021-09-01 10:17:19.055  - info: fritzdect.0 (2949) finished creating templates (if any)
2021-09-01 10:17:19.055  - info: fritzdect.0 (2949) start initial updating devices/groups
2021-09-01 10:17:19.055  - error: fritzdect.0 (2949) fritzbox returned this {"msg":"get error in http request","function":"get_login_state","error":{}}
2021-09-01 10:17:19.055  - error: fritzdect.0 (2949) no response part in returned message
```

</body>
</html>`

Der Logintest per pyhon3 funktioniert:
```
python3 fritz.py "http://192.168.X.X" "mein_FB_user" "mein_FB_passwort"
Falling back to MD5
Successful login for user: iobroker
sid: 7e1ddabb991a5cfd
```

Wenn ich das gleiche mit https versuche produziert es allerdings Fehlermeldungen:

```
python3 fritz.py "https://192.168.X.X" "mein_FB_user" "mein_FB_passwort"
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1421, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fritz.py", line 31, in get_sid
    state = get_login_state(box_url)
  File "fritz.py", line 56, in get_login_state
    http_response = urllib.request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)>


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fritz.py", line 120, in <module>
    main()
  File "fritz.py", line 114, in main
    sid = get_sid(url, username, password)
  File "fritz.py", line 33, in get_sid
    raise Exception("failed to get challenge") from ex
Exception: failed to get challenge
```

**Hier Infos zum System:**
Betriebssystem: linux (Proxmox LXC Container)
Architektur: x64
CPUs: 2
Geschwindigkeit: 3662 MHz
Modell: Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
RAM: 2 GB
Node.js: v12.22.5 (Es gibt eine neuere Version: v12.22.6)
NPM: 6.14.14

Vielen Dank!

Tony

**Comment by tonyblue2** [comment]
Ich habe hier die Lösung gefunden:

https://github.com/foxthefox/ioBroker.fritzdect/issues/61

Aus irgend einem Grund ist das  "http://" vor der IP-Adresse im Adapter verschwunden.

**Comment by foxthefox** [comment]
ja das http:// ist wichtig im Input Feld.
https:// geht derzeitig nicht wegen Zertifikatkram
