### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by aemaething** [foxthefox/ioBroker.fritzdect#3]
Hey,

did I configure something wrong?
Thanks in advance.

**Logfile**
host.raspberrypi	2017-03-03 19:20:47.350	info	Restart adapter system.adapter.fritzdect.0 because enabled
host.raspberrypi	2017-03-03 19:20:47.350	error	instance system.adapter.fritzdect.0 terminated with code 0 (OK)
fritzdect.0	2017-03-03 19:20:47.327	info	terminating
fritzdect.0	2017-03-03 19:20:47.321	info	cleaned everything up...
fritzdect.0	2017-03-03 19:20:47.319	error	at Timer.listOnTimeout (timers.js:119:15)
fritzdect.0	2017-03-03 19:20:47.319	error	at null._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2870:38)
fritzdect.0	2017-03-03 19:20:47.319	error	at Adapter.emit (events.js:110:17)
fritzdect.0	2017-03-03 19:20:47.319	error	at Adapter. (/opt/iobroker/node_modules/iobroker.fritzdect/main.js:48:17)
fritzdect.0	2017-03-03 19:20:47.319	error	TypeError: undefined is not a function
fritzdect.0	2017-03-03 19:20:47.314	error	uncaught exception: undefined is not a function
fritzdect.0	2017-03-03 19:20:10.771	info	polling! fritzdect is alive

**Comment by aemaething** [comment]
Upsie, sry. My node version was too old.
Updated to v4.8.0 and everything's fine. Thx.
