### ISSUE TITLE
Object wrong type

### ISSUE THREAD

**Issue by Ilovegym66** [foxthefox/ioBroker.fritzdect#70]
Number wird mit Text beschrieben:
`

ogo.0 | 2020-03-19 19:09:42.082 | warn | (3885) Value of state fritzdect.0.Comet_119601017160.battery has wrong type
-- | -- | -- | --
iogo.0 | 2020-03-19 19:09:42.082 | warn | (3885) Value of state fritzdect.0.Comet_119610287536.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.082 | warn | (3885) Value of state fritzdect.0.Comet_119600189512.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.082 | warn | (3885) Value of state fritzdect.0.Comet_119590824920.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.082 | warn | (3885) Value of state fritzdect.0.Comet_119600189312.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.081 | warn | (3885) Value of state fritzdect.0.Comet_119600089920.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.081 | warn | (3885) Value of state fritzdect.0.Comet_119600090160.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.081 | warn | (3885) Value of state fritzdect.0.Comet_119600189000.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.081 | warn | (3885) Value of state fritzdect.0.Comet_119590824888.battery has wrong type
iogo.0 | 2020-03-19 19:09:42.080 | warn | (3885) Value of state fritzdect.0.Comet_119600090480.battery has wrong type

`

**Comment by foxthefox** [comment]
The state battery is a percentage value, which is a number.
The state batterylow is an indicator, which is a boolean.

May be it helps if you post some more information, when you want to have help.

**Comment by Ilovegym66** [comment]
Adapter iobroker.iogo send this message after every restart. Looks like the content of value.battery is not a number? Ask for details developer of iobroker.iogo, please.
https://github.com/nisiode/ioBroker.iogo

**Comment by foxthefox** [comment]
additionally I put a parseInt to the value to make sure, that it is a number,
you can check the update 0.3.2 via github installation icon
I hope it is now better functioning

**Comment by Ilovegym66** [comment]
Hi, Version 0.3.2 and 0.3.1 start with this:
`2020-03-20 18:36:27.194  - info: host.iobroker instance system.adapter.fritzdect.0 started with pid 15577
2020-03-20 18:36:27.644  - info: host.iobroker instance system.adapter.vis.0 terminated while should be started once
2020-03-20 18:36:27.674  - error: host.iobroker Caught by controller[0]: /opt/iobroker/node_modules/iobroker.fritzdect/main.js:1907
2020-03-20 18:36:27.674  - error: host.iobroker Caught by controller[0]:                                 currentMode = "Night;
2020-03-20 18:36:27.674  - error: host.iobroker Caught by controller[0]:                                               ^^^^^^^
2020-03-20 18:36:27.674  - error: host.iobroker Caught by controller[0]: SyntaxError: Invalid or unexpected token
2020-03-20 18:36:27.674  - error: host.iobroker Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:723:23)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at startup (internal/bootstrap/node.js:283:19)
2020-03-20 18:36:27.675  - error: host.iobroker Caught by controller[0]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2020-03-20 18:36:27.675  - error: host.iobroker instance system.adapter.fritzdect.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
`

**Comment by foxthefox** [comment]
Sorry, there was a typo.
The version now on github is OK.

**Comment by Ilovegym66** [comment]
is fixed
